echo "ENTER YOUR NAME:"
read NAME
echo "ENTER YOUR AGE:"
read AGE
echo "ENTER YOUR FAVORITE PROGRAMMING LANGUAGE:"
read PROGRAMMINGFAV

echo "THANK YOU $NAME, YOU ARE $AGE YEARS OLD & YOUR FAVORITE PROGRAMMING LANGUAGE IS $PROGRAMMINGFAV." 